[package]
name = "botwaf-cmd"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Other modules dependencies.
botwaf-server.workspace = true
botwaf-updater.workspace = true
botwaf-verifier.workspace = true
botwaf-types.workspace = true
botwaf-utils.workspace = true

# Thirdparty dependencies.
clap.workspace = true
anyhow.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
mimalloc.workspace = true
tokio.workspace = true
axum.workspace = true
axum-prometheus.workspace = true
tower.workspace = true
tower-http.workspace = true
tower-cookies.workspace = true
lazy_static.workspace = true
log.workspace = true
tracing.workspace = true

[[bin]]
name = "botwaf"
path = "src/bin/botwaf.rs"

[build-dependencies]
chrono.workspace = true
